/** Curated services per architecture: OpenRouter as separate rows, no Gemini direct. */
export const CATALOG = [
  {
    serviceId: "openrouter_qwen3_coder_free",
    name: "Qwen3 Coder (free) via OpenRouter",
    provider: "OpenRouter",
    providerServiceId: "qwen/qwen3-coder:free",
    adapterType: "openrouter",
    capabilities: ["code_generation", "tool_use", "agentic_coding", "llm"],
    description: "Free coding model for repositories, tools, and agentic dev tasks.",
    modelCard: "Strong for code generation and tool orchestration. Latency can vary on free tier.",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.78,
  },
  {
    serviceId: "openrouter_qwen3_next_free",
    name: "Qwen3 Next 80B (free) via OpenRouter",
    provider: "OpenRouter",
    providerServiceId: "qwen/qwen3-next-80b-a3b-instruct:free",
    adapterType: "openrouter",
    capabilities: ["reasoning", "long_context", "llm", "instruction"],
    description: "General instruction, RAG, and long-context work on a large instruct model.",
    modelCard: "Good default for multi-step agent reasoning when cost must be zero.",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.76,
  },
  {
    serviceId: "tavily_search",
    name: "Tavily search",
    provider: "Tavily",
    providerServiceId: "search",
    adapterType: "tavily",
    capabilities: ["web_research", "search", "agent_native"],
    description: "Agent-native web search with concise answers and sources.",
    modelCard: "Best for up-to-date facts and link-backed answers.",
    estimatedBaseCostUsd: 0.02,
    trustScoreSeed: 0.82,
  },
  {
    serviceId: "exa_neural",
    name: "Exa neural search",
    provider: "Exa",
    providerServiceId: "search",
    adapterType: "exa",
    capabilities: ["web_research", "search", "semantic"],
    description: "Semantic + neural search for research agents.",
    modelCard: "Use when you need page contents, not just snippets.",
    estimatedBaseCostUsd: 0.03,
    trustScoreSeed: 0.8,
  },
  {
    serviceId: "serper_google",
    name: "Serper SERP",
    provider: "Serper",
    providerServiceId: "serp",
    adapterType: "serper",
    capabilities: ["web_research", "serp", "search"],
    description: "Google-style SERP results for agents.",
    modelCard: "Fallback when you need traditional SERP layout.",
    estimatedBaseCostUsd: 0.01,
    trustScoreSeed: 0.74,
  },
  {
    serviceId: "firecrawl_scrape",
    name: "Firecrawl extract",
    provider: "Firecrawl",
    providerServiceId: "scrape",
    adapterType: "firecrawl",
    capabilities: ["extraction", "web_extraction", "markdown"],
    description: "Turn pages into clean markdown for downstream LLMs.",
    modelCard: "Use after search when you need full article text.",
    estimatedBaseCostUsd: 0.02,
    trustScoreSeed: 0.79,
  },
  {
    serviceId: "apify_crawler",
    name: "Apify generic run",
    provider: "Apify",
    providerServiceId: "actor",
    adapterType: "apify",
    capabilities: ["extraction", "automation", "scraping"],
    description: "Prebuilt scrapers and automation for structured extraction.",
    modelCard: "Heavier jobs; use when you need a hosted browser.",
    estimatedBaseCostUsd: 0.05,
    trustScoreSeed: 0.72,
  },
  {
    serviceId: "resend_email",
    name: "Resend email API",
    provider: "Resend",
    providerServiceId: "email",
    adapterType: "resend",
    capabilities: ["email", "outbound", "agentic_email"],
    description: "Transactional email send for agent-originated follow-ups.",
    modelCard: "Server-side; requires configured sender domain in production.",
    estimatedBaseCostUsd: 0.0,
    trustScoreSeed: 0.85,
  },
  {
    serviceId: "elevenlabs_tts",
    name: "ElevenLabs TTS",
    provider: "ElevenLabs",
    providerServiceId: "tts",
    adapterType: "elevenlabs",
    capabilities: ["voice", "tts", "audio"],
    description: "High-quality text-to-speech and voiceover.",
    modelCard: "Use when the task output must be spoken audio.",
    estimatedBaseCostUsd: 0.15,
    trustScoreSeed: 0.8,
  },
  {
    serviceId: "deepgram_stt",
    name: "Deepgram STT",
    provider: "Deepgram",
    providerServiceId: "stt",
    adapterType: "deepgram",
    capabilities: ["voice", "stt", "transcription", "audio"],
    description: "Fast speech-to-text for voice agents.",
    modelCard: "Ingest user audio to text for downstream models.",
    estimatedBaseCostUsd: 0.04,
    trustScoreSeed: 0.77,
  },
  // --- Demo catalog (no API keys): link provider_products to these service_ids ---
  {
    serviceId: "demo_echo_capsule",
    name: "Demo: Echo capsule",
    provider: "AgentValue",
    providerServiceId: "demo_echo",
    adapterType: "demo_static",
    capabilities: ["demo", "echo", "agent", "smoke_test"],
    description: "Returns your message — instant invoke for wiring tests.",
    modelCard: "Input: message, query, or prompt (any string).",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.7,
  },
  {
    serviceId: "demo_product_catalog",
    name: "Demo: Product SKU dataset",
    provider: "AgentValue",
    providerServiceId: "demo_product_catalog",
    adapterType: "demo_static",
    capabilities: ["demo", "dataset", "catalog", "tabular"],
    description: "Five fake inventory rows; optional filter by category.",
    modelCard: "Optional input: category (hardware | software | dataset | services).",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.72,
  },
  {
    serviceId: "demo_hackathon_teams",
    name: "Demo: Hackathon teams table",
    provider: "AgentValue",
    providerServiceId: "demo_hackathon_teams",
    adapterType: "demo_static",
    capabilities: ["demo", "dataset", "tabular", "events"],
    description: "Static team roster for UI demos and marketplace screenshots.",
    modelCard: "No required input; returns four sample teams.",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.71,
  },
  {
    serviceId: "demo_sentiment_toy",
    name: "Demo: Toy sentiment labeler",
    provider: "AgentValue",
    providerServiceId: "demo_sentiment_toy",
    adapterType: "demo_static",
    capabilities: ["demo", "classification", "nlp", "agent"],
    description: "Fake sentiment from text length — illustrates a cheap NLP slot.",
    modelCard: "Input: text or message (string).",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.68,
  },
  {
    serviceId: "demo_world_capitals",
    name: "Demo: Country → capital lookup",
    provider: "AgentValue",
    providerServiceId: "demo_world_capitals",
    adapterType: "demo_static",
    capabilities: ["demo", "dataset", "lookup", "geo"],
    description: "Tiny key–value dataset (five countries) for lookup demos.",
    modelCard: "Input: country (france | japan | kenya | brazil | canada).",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.73,
  },
] as const;
