/** Curated services per architecture: OpenRouter as separate rows, no Gemini direct. */
export const CATALOG = [
  {
    serviceId: "openrouter_qwen3_coder_free",
    name: "Qwen3 Coder (free) via OpenRouter",
    provider: "OpenRouter",
    providerServiceId: "qwen/qwen3-coder:free",
    adapterType: "openrouter",
    capabilities: ["code_generation", "tool_use", "agentic_coding", "llm"],
    description: "Free coding model for repositories, tools, and agentic dev tasks.",
    modelCard: "Strong for code generation and tool orchestration. Latency can vary on free tier.",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.78,
  },
  {
    serviceId: "openrouter_qwen3_next_free",
    name: "Qwen3 Next 80B (free) via OpenRouter",
    provider: "OpenRouter",
    providerServiceId: "qwen/qwen3-next-80b-a3b-instruct:free",
    adapterType: "openrouter",
    capabilities: ["reasoning", "long_context", "llm", "instruction"],
    description: "General instruction, RAG, and long-context work on a large instruct model.",
    modelCard: "Good default for multi-step agent reasoning when cost must be zero.",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.76,
  },
  {
    serviceId: "tavily_search",
    name: "Tavily search",
    provider: "Tavily",
    providerServiceId: "search",
    adapterType: "tavily",
    capabilities: ["web_research", "search", "agent_native"],
    description: "Agent-native web search with concise answers and sources.",
    modelCard: "Best for up-to-date facts and link-backed answers.",
    estimatedBaseCostUsd: 0.02,
    trustScoreSeed: 0.82,
  },
  {
    serviceId: "exa_neural",
    name: "Exa neural search",
    provider: "Exa",
    providerServiceId: "search",
    adapterType: "exa",
    capabilities: ["web_research", "search", "semantic"],
    description: "Semantic + neural search for research agents.",
    modelCard: "Use when you need page contents, not just snippets.",
    estimatedBaseCostUsd: 0.03,
    trustScoreSeed: 0.8,
  },
  {
    serviceId: "serper_google",
    name: "Serper SERP",
    provider: "Serper",
    providerServiceId: "serp",
    adapterType: "serper",
    capabilities: ["web_research", "serp", "search"],
    description: "Google-style SERP results for agents.",
    modelCard: "Fallback when you need traditional SERP layout.",
    estimatedBaseCostUsd: 0.01,
    trustScoreSeed: 0.74,
  },
  {
    serviceId: "firecrawl_scrape",
    name: "Firecrawl extract",
    provider: "Firecrawl",
    providerServiceId: "scrape",
    adapterType: "firecrawl",
    capabilities: ["extraction", "web_extraction", "markdown"],
    description: "Turn pages into clean markdown for downstream LLMs.",
    modelCard: "Use after search when you need full article text.",
    estimatedBaseCostUsd: 0.02,
    trustScoreSeed: 0.79,
  },
  {
    serviceId: "apify_crawler",
    name: "Apify generic run",
    provider: "Apify",
    providerServiceId: "actor",
    adapterType: "apify",
    capabilities: ["extraction", "automation", "scraping"],
    description: "Prebuilt scrapers and automation for structured extraction.",
    modelCard: "Heavier jobs; use when you need a hosted browser.",
    estimatedBaseCostUsd: 0.05,
    trustScoreSeed: 0.72,
  },
  {
    serviceId: "resend_email",
    name: "Resend email API",
    provider: "Resend",
    providerServiceId: "email",
    adapterType: "resend",
    capabilities: ["email", "outbound", "agentic_email"],
    description: "Transactional email send for agent-originated follow-ups.",
    modelCard: "Server-side; requires configured sender domain in production.",
    estimatedBaseCostUsd: 0.0,
    trustScoreSeed: 0.85,
  },
  {
    serviceId: "elevenlabs_tts",
    name: "ElevenLabs TTS",
    provider: "ElevenLabs",
    providerServiceId: "tts",
    adapterType: "elevenlabs",
    capabilities: ["voice", "tts", "audio"],
    description: "High-quality text-to-speech and voiceover.",
    modelCard: "Use when the task output must be spoken audio.",
    estimatedBaseCostUsd: 0.15,
    trustScoreSeed: 0.8,
  },
  {
    serviceId: "deepgram_stt",
    name: "Deepgram STT",
    provider: "Deepgram",
    providerServiceId: "stt",
    adapterType: "deepgram",
    capabilities: ["voice", "stt", "transcription", "audio"],
    description: "Fast speech-to-text for voice agents.",
    modelCard: "Ingest user audio to text for downstream models.",
    estimatedBaseCostUsd: 0.04,
    trustScoreSeed: 0.77,
  },
  // --- Deployable HTTP agents (see repo /demo-agent-apis): seller sets base URL on the product ---
  {
    serviceId: "external_agent_echo",
    name: "HTTP agent: Echo",
    provider: "AgentValue (template)",
    providerServiceId: "echo_v1",
    adapterType: "http_external",
    capabilities: ["http", "agent", "echo", "exchange"],
    description:
      "Deploy `demo-agent-apis/echo`, expose POST /invoke, then paste your public origin as the product base URL.",
    modelCard:
      "Contract: POST /invoke JSON { task, input }. Echo reads input.message | input.query | input.prompt. Repo: demo-agent-apis/echo/README.md",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.7,
  },
  {
    serviceId: "external_agent_product_catalog",
    name: "HTTP agent: Product catalog",
    provider: "AgentValue (template)",
    providerServiceId: "product_catalog_v1",
    adapterType: "http_external",
    capabilities: ["http", "agent", "dataset", "tabular"],
    description: "Deploy `demo-agent-apis/product-catalog` — five SKU rows, optional input.category filter.",
    modelCard:
      "Contract: POST /invoke { task, input }. Optional input.category ∈ hardware|software|dataset|services. Repo: demo-agent-apis/product-catalog/README.md",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.72,
  },
  {
    serviceId: "external_agent_hackathon_teams",
    name: "HTTP agent: Hackathon teams",
    provider: "AgentValue (template)",
    providerServiceId: "teams_v1",
    adapterType: "http_external",
    capabilities: ["http", "agent", "dataset", "events"],
    description: "Deploy `demo-agent-apis/hackathon-teams` — static four-team JSON table.",
    modelCard: "Contract: POST /invoke { task, input }. Input ignored. Repo: demo-agent-apis/hackathon-teams/README.md",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.71,
  },
  {
    serviceId: "external_agent_sentiment",
    name: "HTTP agent: Toy sentiment",
    provider: "AgentValue (template)",
    providerServiceId: "sentiment_v1",
    adapterType: "http_external",
    capabilities: ["http", "agent", "classification", "nlp"],
    description: "Deploy `demo-agent-apis/sentiment` — deterministic toy label from text length.",
    modelCard:
      "Contract: POST /invoke { task, input }. Uses input.text | input.message. Repo: demo-agent-apis/sentiment/README.md",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.68,
  },
  {
    serviceId: "external_agent_capitals",
    name: "HTTP agent: Country capitals",
    provider: "AgentValue (template)",
    providerServiceId: "capitals_v1",
    adapterType: "http_external",
    capabilities: ["http", "agent", "dataset", "lookup"],
    description: "Deploy `demo-agent-apis/capitals` — lookup capital for five countries.",
    modelCard:
      "Contract: POST /invoke { task, input }. input.country ∈ france|japan|kenya|brazil|canada. Repo: demo-agent-apis/capitals/README.md",
    estimatedBaseCostUsd: 0,
    trustScoreSeed: 0.73,
  },
] as const;
